### PR TITLE
Csv upload

### PR DESCRIPTION
**Pull request by jmaerte**
moved time slide toggle
added skip/abort/keep
breakpoints
new alignment
number spinner(header col) to material style
added error handling(http error if header col has no value, text comes from backend in fields status, statusText, name)

### CODE REVIEW

**Comment by ChristianBeilschmidt** [comment]
You have implemented the code comments well.

However, you still need to tackle the three points:
 * circular dependecies
 * text qualifier
 * separation of layer name and error behavior from data types

Furthermore, you should include a description about enabling temporal properties.
grafik
There should be a sentence like: "The file include temporal information <check>".

**Comment by ChristianBeilschmidt** [comment]
I found a bug: The temporal selection value `start+constant`does not work. The query should be either `start` with duration `inf` or with a value in seconds.

**Comment by ChristianBeilschmidt** [comment]
There are just two things left:

1. The removal of the circular dependencies.
2. The fixing of start + const time selection. This crashed in a previous version, by now the user cannot type in a duration.

grafik

**Comment by jmaerte** [comment]
csvsource

Even with that query it crashes. I fixed a bug where one of the columns were not typed in the constant duration query but that didn't fix the problem.

**Comment by ChristianBeilschmidt** [comment]
Can you pull the current master? There are conflicting changes for `package.json` and `src/app/app.module.ts`. Until then I cannot merge this pull request.

**Comment by jmaerte** [comment]
1. WKT is not selected by default anymore, but when you initially only have one column(for example if you upload semicolon-delimited csv and it initially parses it comma-delimited) it sets wkt to true, since one-column files only allow wkt.
2. flower.csv works fine for me now.
3. width limit is now set to 500px. An example of this limiting can be seen using the csv from 4.
4. Works fine for me now.

**Comment by ChristianBeilschmidt** [comment]
WKT works great now. The width limit is useful I guess.

Unfortunately, it still always selects WKT as default. When I choose flower then - although it is initially parsed correctly with comma - it selects WKT.

You should, when you *first* visit the spatial page, decide whether you have only one column and choose WKT. Otherwise, just let it be x and y.

**Pull request merged**
